PACKAGE_NAME="fl2000drm"
PACKAGE_VERSION="1.9"
BUILT_MODULE_NAME[0]="fl2000drm"
BUILT_MODULE_LOCATION[0]="driver"
MAKE[0]="make -C driver KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C driver clean"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
